# Site settings
title: Dawn Delatte
email: dawndelatte@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#   This is the portfolio and journal site for an Austin-based designer, Dawn Delatte.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "dawndelatte.github.io" # the base hostname & protocol for your site
twitter_username: dawndig
github_username:  dawndelatte

# Build settings
markdown: kramdown
paginate: 9